[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "cerulean"
ADMIN_NAME = "Econovolt [Projeto Integrador]"
ADMIN_TEMPLATE_MODE = "bootstrap2"
EXTENSIONS = [
    "app.ext.db:init_app",
    "app.ext.auth:init_app", 
    "app.ext.admin:init_app", 
    "app.ext.migrate:init_app", 
    "app.ext.cli:init_app", 
    "app.ext.site:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///econovolt.db" 
SQLALCHEMY_TRACK_MODIFICATIONS = false 
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER-ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
ADMIN_NAME = "Econovolt (dev mode)"
EXTENSIONS = [
    "app.ext.db:init_app",
    "app.ext.auth:init_app", 
    "app.ext.admin:init_app", 
    "app.ext.migrate:init_app", 
    "app.ext.cli:init_app", 
    "app.ext.toolbar:init_app", 
    "app.ext.site:init_app",    
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "sqlite:///econovolt.db" 
